import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "./components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import QueryProvider from "@/app/util/QueryProvider";
import "@smastrom/react-rating/style.css";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  style: "normal",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <QueryProvider>
      <ClerkProvider>
        <html lang="en">
          <body className={poppins.className}>
            <Navbar>{children}</Navbar>
          </body>
        </html>
      </ClerkProvider>
    </QueryProvider>
  );
}
