import './globals.css'
import { Poppins } from 'next/font/google'
import Nav from './components/Nav'
const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  style: "normal",
})
import RecoilProvider from './util/recoil/RecoilProvider'
import '@smastrom/react-rating/style.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {

  return (
    <RecoilProvider>
      <html lang="en">
        <body className={poppins.className}>
          <Nav />

          {children}
        </body>
      </html>
    </RecoilProvider>
  )
}
