"use client"
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ugqLzLpSVSF
 */
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

import { iProduct, iReview } from '@/app/util/Interfaces'; // Update with the actual path
import Image from 'next/image';
import RatingModuleReadOnly from '@/app/components/RatingModuleReadOnly';
import { useState } from 'react';
import Link from 'next/link';
import YesNoAlert from '@/app/components/YesNoAlert';
import { useQuery } from '@tanstack/react-query';
import { getReviews } from '@/app/util/serverFunctions';
import { calculateAverageReviewRating } from '@/app/util/calculateAverageReviewRating';
import LoadingSpinner from '@/app/components/LoadingSpinner';
import VerticalLinks from '@/app/components/VerticalLinks';
interface ProductCardProps {
  reviews?: iReview[] | null
  options: {
    showLatestReview: boolean;
    size: string;
    showWriteReview: boolean;
    showClaimThisProduct: boolean;
  };
  product?: iProduct | null
}
interface iCalculatedRating {
  roundedRating: number;
  roundedRatingOneDecimalPlace: number;
  numberOfReviews: number;
}
const FullProductCard: React.FC<ProductCardProps> = ({ reviews, options, product }) => {
  const [showModal, setShowModal] = useState(false);

  const currentProduct = reviews && reviews.length > 0 ? reviews[0].product : product;

  const { data, isLoading, isError, error } = useQuery({
    queryKey: ["reviews", currentProduct?.id],
    queryFn: () => getReviews(currentProduct?.id!),
    refetchOnWindowFocus: false,
    enabled: !!currentProduct && !reviews, // Only fetch if product is provided and reviews are not
  }) as any

  const allReviews = reviews || data?.data || [];
  // const totalComments = allReviews.reduce((accumulator, review) => accumulator + review.comments.length, 0);

  if (isLoading) return <LoadingSpinner />
  if (isError) return <p>{error.message}</p>

  let { roundedRating, roundedRatingOneDecimalPlace, numberOfReviews } = calculateAverageReviewRating(allReviews) as unknown as iCalculatedRating
  return (
    <Card className="max-w-lg mx-auto bg-white rounded-lg shadow-md overflow-hidden">
      <CardContent>
        <div className="flex items-start space-x-4 p-5">
          <img
            alt="Maad 97.5FM Logo"
            className="h-24 w-24 rounded-lg bg-gray-200"
            height="100"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/100",
              objectFit: "cover",
            }}
            width="100"
          />
          <div className="flex flex-col justify-between">
            <div>
              <h3 className="text-xl font-semibold text-gray-900">Maad 97.5FM</h3>
              <p className="text-sm text-gray-500">166 Waterloo street, Georgetown</p>
              <p className="text-sm text-gray-500">Your go-to station for the latest hits and entertainment.</p>
              <div className="flex items-center mt-2">
                <div className="flex items-center">
                  <StarIcon className="text-yellow-400 w-5 h-5" />
                  <StarIcon className="text-yellow-400 w-5 h-5" />
                  <StarIcon className="text-yellow-400 w-5 h-5" />
                  <StarIcon className="text-yellow-400 w-5 h-5" />
                  <StarIcon className="text-gray-300 w-5 h-5" />
                </div>
                <span className="ml-2 text-sm font-medium text-gray-600">4.0 (5 reviews)</span>
              </div>
            </div>
            <div className="flex space-x-2">
              <Button className="mt-4" variant="outline">
                Claim this product
              </Button>
              <Button className="mt-4">Write Review</Button>
            </div>
          </div>
          <div className="flex flex-col space-y-3 justify-between ml-4">
            <HomeIcon className="text-gray-400 w-6 h-6" />
            <MailboxIcon className="text-gray-400 w-6 h-6" />
            <PhoneIcon className="text-gray-400 w-6 h-6" />
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
export default FullProductCard

function StarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function HomeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function MailboxIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 17a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9.5C2 7 4 5 6.5 5H18c2.2 0 4 1.8 4 4v8Z" />
      <polyline points="15,9 18,9 18,11" />
      <path d="M6.5 5C9 5 11 7 11 9.5V17a2 2 0 0 1-2 2v0" />
      <line x1="6" x2="7" y1="10" y2="10" />
    </svg>
  )
}


function PhoneIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}
