/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PTF0GWWLjFG
 */
import Link from "next/link";
import { CardContent, Card, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { iUser } from "@/app/util/Interfaces";
import Image from "next/image";

interface UserInfoProps {
  user: iUser;
}
export const MyActivity: React.FC<UserInfoProps> = ({ user }) => {
  return (
    <div className="grid md:grid-cols-2 gap-4 items-start">
      <div className="space-y-4">
        <div className="space-y-2">
          <h1 className="text-2xl font-bold">My Activity</h1>
          <p className="text-gray-500 dark:text-gray-400">
            View your recent activity
          </p>
        </div>
        <div className="space-y-4">
          <div className="flex items-center space-x-2">
            {user.avatar && (
              <Image
                src={user.avatar}
                alt={user.firstName}
                className="w-10 h-10 rounded-full mr-4 object-cover"
                width={40}
                height={40}
              />
            )}
            <div className="space-y-1.5">
              <p className="font-medium">
                {user.firstName} {user.lastName}
              </p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                {user.email}
              </p>
            </div>
          </div>
          <div className="grid grid-cols-3 items-center gap-4">
            <Link
              className="flex items-center space-x-2 p-2 rounded-md bg-gray-100 dark:bg-gray-800"
              href="#"
            >
              <HeartIcon className="w-6 h-6" />
              <span className="text-sm font-medium">Likes</span>
            </Link>
            <Link
              className="flex items-center space-x-2 p-2 rounded-md"
              href="#"
            >
              <StarIcon className="w-6 h-6" />
              <span className="text-sm font-medium">Reviews</span>
            </Link>
            <Link
              className="flex items-center space-x-2 p-2 rounded-md"
              href="#"
            >
              <MessageSquareIcon className="w-6 h-6" />
              <span className="text-sm font-medium">Comments</span>
            </Link>
          </div>
        </div>
        <Card>
          <CardContent className="space-y-4">
            <div className="flex items-center space-x-2">
              <HeartIcon className="w-6 h-6" />
              <div className="space-y-1">
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  You liked a review
                </p>
                <p className="text-sm font-medium">Great service!</p>
              </div>
            </div>
            <div className="flex items-center space-x-2">
              <StarIcon className="w-6 h-6" />
              <div className="space-y-1">
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  You reviewed a company
                </p>
                <p className="text-sm font-medium">Acme Inc</p>
              </div>
            </div>
            <div className="flex items-center space-x-2">
              <MessageSquareIcon className="w-6 h-6" />
              <div className="space-y-1">
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  You commented on a review
                </p>
                <p className="text-sm font-medium">Well said!</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
      <Card className="grid gap-4 p-0">
        <CardHeader className="p-4">
          <Input
            className="w-full sm:w-[400px] max-w-none"
            placeholder="Search activity..."
            type="text"
          />
        </CardHeader>
        <CardContent className="p-0">
          <div className="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-800">
            <div className="flex items-center space-x-2">
              <ClockIcon className="w-6 h-6" />
              <div className="space-y-1.5">
                <p className="text-sm font-medium">Recent activity</p>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Showing recent activity
                </p>
              </div>
            </div>
            <div>
              <div className="rounded-full p-2 hover:bg-gray-100 dark:hover:bg-gray-800">
                <MoreHorizontalIcon className="w-4 h-4" />
              </div>
              <div>
                <div>
                  <div>
                    <FileEditIcon className="w-4 h-4 mr-2" />
                    Edit
                  </div>
                  <div>
                    <TrashIcon className="w-4 h-4 mr-2" />
                    Delete
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="p-4">
            <div className="grid grid-cols-3 items-start gap-4 text-sm">
              <div className="flex items-center space-x-2">
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="40"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "40/40",
                    objectFit: "cover",
                  }}
                  width="40"
                />
                <div className="space-y-1.5">
                  <p className="font-medium">John Doe</p>
                  <p className="text-xs text-gray-500 dark:text-gray-400">
                    johndoe@example.com
                  </p>
                </div>
              </div>
              <div className="space-y-2 col-span-2">
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  You liked a review
                </p>
                <p className="text-sm font-medium">Great service!</p>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

function HeartIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>
  );
}

function StarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}

function MessageSquareIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
    </svg>
  );
}

function ClockIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  );
}

function MoreHorizontalIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="1" />
      <circle cx="19" cy="12" r="1" />
      <circle cx="5" cy="12" r="1" />
    </svg>
  );
}

function FileEditIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 13.5V4a2 2 0 0 1 2-2h8.5L20 7.5V20a2 2 0 0 1-2 2h-5.5" />
      <polyline points="14 2 14 8 20 8" />
      <path d="M10.42 12.61a2.1 2.1 0 1 1 2.97 2.97L7.95 21 4 22l.99-3.95 5.43-5.44Z" />
    </svg>
  );
}

function TrashIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  );
}
